### ISSUE TITLE
How to ues it?

### ISSUE THREAD

**Issue by mrlinyj** [mgmacias95/Flower-Recognition#1]
when I try to python mian.py
it 
![image](https://user-images.githubusercontent.com/35088451/38970049-ea85cbc6-43c5-11e8-9cd1-2f70c73629f5.png)
what should I do ?

**Comment by Data-Scientist-Singh** [comment]
for me its says
 Traceback (most recent call last):
  File "C:\Users\tanve\Desktop\Flower-Recognition-master\model.py", line 2, in <module>
    from sklearn.svm import SVC
  File "C:\Users\tanve\AppData\Local\Programs\Python\Python36\lib\site-packages\sklearn\__init__.py", line 133, in <module>
    from . import __check_build
ImportError: cannot import name '__check_build'
